# Generated by Django 3.1.6 on 2021-02-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_user_param', models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Param')),
                ('file_user_vars', models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Vars File')),
                ('file_user_vals', models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Vals File')),
                ('file_user_weight', models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Weight File')),
                ('file_user_base', models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Date Base')),
                ('status', models.CharField(default='Upload', max_length=50)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
