# Generated by Django 3.1.6 on 2021-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.FileField(db_index=True, default='2021-02-07 16:30:41.652304', upload_to=''),
        ),
    ]
