# Generated by Django 3.0.4 on 2021-01-28 08:16

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='file_user_base',
            field=models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Date Base'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_param',
            field=models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Param'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_vals',
            field=models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Vals File'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_vars',
            field=models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Vars File'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_weight',
            field=models.FileField(upload_to=profile_user.models.user_directory_path, verbose_name='Weight File'),
        ),
    ]
