# Generated by Django 3.0.4 on 2021-02-05 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_auto_20210205_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.FileField(db_index=True, default=datetime.datetime(2021, 2, 5, 19, 46, 22, 212458), upload_to=''),
        ),
    ]
