# Generated by Django 3.1.6 on 2021-02-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_auto_20210207_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.FileField(default='2021-02-07 17:56:06.765862', upload_to=''),
        ),
    ]
