# Generated by Django 3.0.2 on 2020-04-06 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_user', '0002_auto_20200402_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
