# Generated by Django 3.1.6 on 2021-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_auto_20210207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.CharField(db_index=True, default='2021-02-07 18:00:39.408344', max_length=50),
        ),
    ]
