# Generated by Django 3.0.4 on 2021-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_auto_20210207_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfile',
            name='comand',
            field=models.CharField(choices=[('RU', 'Ruby-Ru'), ('EN', 'Ruby-En'), ('DF', 'Convert')], default=1, max_length=50, verbose_name='Параметр формата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customfile',
            name='created',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
