# Generated by Django 3.0.4 on 2021-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_auto_20210301_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='comand',
            field=models.CharField(choices=[('Ruby-RU', 'Ruby-Ru'), ('Ruby-EN', 'Ruby-En'), ('convert', 'Convert')], max_length=50, verbose_name='Параметр формата'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название волны/исследования'),
        ),
    ]
