# Generated by Django 3.0.4 on 2021-03-11 08:22

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_auto_20210305_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfile',
            name='log',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LogFile'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_vals',
            field=models.FileField(blank=True, null=True, upload_to=profile_user.models.user_directory_path, verbose_name='Vals File'),
        ),
        migrations.AlterField(
            model_name='customfile',
            name='file_user_weight',
            field=models.FileField(blank=True, null=True, upload_to=profile_user.models.user_directory_path, verbose_name='Weight File'),
        ),
    ]
